# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 698bac762c2b55bf9055faa764e8080004eb9c0491041eab3a835c7c53277b7611827cb0bebace35563a31c568d02f732ac16233bce7cae3421ae49d729a9afd

test:
  secret_key_base: cf6fb58071a8ba1fc95616a316e463ce27de60d84df8e75221696c25974a681f6d3303e6b27d5396127204340a4408846bd2aceb5c1bc593943d7b3fcdd384a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
